name: netflix
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4


#use google ml tootlkit for face detection and app open (real device)
#add crashanalytics
#use save form to google sheet (in firebase extension )
#use storage(firebase) and local storage

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get:
  shared_preferences:
  cached_network_image:
  lottie:
  http:
  intl:
  firebase_core:
  firebase_auth:
  font_awesome_flutter:
  google_sign_in:
  get_storage:
  image_picker:
  firebase_crashlytics:
  firebase_database:
  firebase_storage:
  connectivity_plus:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/appLogo/Netflix_app_logo.png"


flutter:

  uses-material-design: true

  assets:
     - assets/splashLogo/
     - assets/Lottie/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
